/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/character.glb -o src/Character.jsx --transform --keepnames --meta 
Files: public/model/character.glb [34.43MB] > /Users/ephriamkassa/Desktop/ollo2/ollo2/src/character-transformed.glb [3.41MB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/character-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/character-transformed.glb')
